services:
  - type: web
    name: linkwatch
    env: python
    plan: free
    region: oregon
    branch: main
    rootDir: .
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /healthz
    autoDeploy: true

    envVars:
      # App config
      - key: RATE_LIMIT_PER_MIN
        value: "10"
      - key: SCAN_CONCURRENCY
        value: "8"
      - key: SCAN_TIMEOUT_SECONDS
        value: "10"
      - key: SCAN_MAX_PAGES_FREE
        value: "150"
      - key: SCAN_MAX_PAGES_HARD
        value: "5000"
      - key: LW_USER_AGENT
        value: "LinkWatch/0.9.0 (+https://example.com)"
      - key: PUBLIC_BASE_URL
        value: "https://linkwatch.onrender.com"
      - key: PLAUSIBLE_DOMAIN
        value: ""
      - key: GOOGLE_SITE_VERIFICATION
        value: ""

      # Use Postgres instead of a disk-backed SQLite file
      - key: DATABASE_URL
        sync: false   # set the real value in the dashboard

      # Email (optional)
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: REPORT_EMAIL_FROM
        sync: false
