services:
  - type: web
    name: linkwatch
    env: python
    plan: free               # upgrade later if needed
    region: oregon           # or frankfurt, singapore, etc.
    branch: main
    rootDir: .
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /healthz
    autoDeploy: true

    # Persist reports & DB across deploys
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1

    envVars:
      # App config (safe to keep in VCS)
      - key: LW_DB_PATH
        value: /var/data/linkwatch.db
      - key: RATE_LIMIT_PER_MIN
        value: "10"
      - key: SCAN_CONCURRENCY
        value: "8"
      - key: SCAN_TIMEOUT_SECONDS
        value: "10"
      - key: SCAN_MAX_PAGES_FREE
        value: "150"
      - key: SCAN_MAX_PAGES_HARD
        value: "5000"
      - key: LW_USER_AGENT
        value: "LinkWatch/0.9.0 (+https://example.com)"
      # Optional analytics/SEO
      - key: PLAUSIBLE_DOMAIN
        value: ""
      - key: GOOGLE_SITE_VERIFICATION
        value: ""
      # Public URL (fill after first deploy or if you have a custom domain)
      - key: PUBLIC_BASE_URL
        value: "https://linkwatch.onrender.com"

      # Secrets — manage in the Render dashboard (won’t be overwritten by YAML)
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: REPORT_EMAIL_FROM
        sync: false
